generated: '2026-07-11'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: zcash.readthedocs.io
  https: true
  tls_version: TLSv1.3
  cert_expires: Aug 27 13:13:23 2026 GMT
  hsts: true
  hsts_max_age: 31536000
- host: 127.0.0.1
  https: false
- host: mainnet.lightwalletd.com
  https: false
domains:
- domain: readthedocs.io
  dnssec: false
  caa:
  - 0 issue "comodoca.com"
  - 0 issue "digicert.com; cansignhttpexchanges=yes"
  - 0 issue "letsencrypt.org"
  - 0 issue "pki.goog; cansignhttpexchanges=yes"
  - 0 issue "ssl.com"
  - 0 issuewild "amazonaws.com"
  spf: false
  dmarc: false
- domain: lightwalletd.com
  dnssec: false
  caa: []
  spf: false
  dmarc: false
